services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .data/mongo:/data/db
    env_file:
      - .env
  express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
